In [1]:
print("Numpy from Quickstart tutorial in Numpy.org")

Numpy from Quickstart tutorial in Numpy.org


In [2]:
import numpy as np

a= np.array([[1,2,3,4,5],
            [5,4,3,2,1]])
print(a)

[[1 2 3 4 5]
 [5 4 3 2 1]]


In [3]:
a.ndim

2

In [4]:
a.size


10

In [5]:
a.shape

(2, 5)

In [6]:
a.dtype


dtype('int32')

In [7]:
a.data


In [8]:
a.itemsize

4

In [9]:
a.dtype.itemsize

4

In [10]:
type(a)

numpy.ndarray

######  Array Creation
There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from
the type of the elements in the sequences.

In [15]:
b = np.array([12,23,33,44,55])
print(b)

[12 23 33 44 55]


In [17]:
b.dtype

dtype('int32')

In [28]:
c=np.array([[1.2,2.2,3.3,4.04],
          [3.5,33.4,44.5,99.09]])
print(c)

[[ 1.2   2.2   3.3   4.04]
 [ 3.5  33.4  44.5  99.09]]


In [29]:
print(c.dtype)
print(c.dtype.itemsize)
print(c.ndim)
print(c.size)
print(c.shape)
print(c.data)

float64
8
2
8
(2, 4)


In [47]:
d = np.array([[1,2,3,4],[6,7,8,9]], dtype=np.float64)
d

array([[1., 2., 3., 4.],
       [6., 7., 8., 9.]])

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [53]:
s= np.zeros((3,3))
print(s)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [68]:
z=np.ones((3,4,4),dtype=np.float64)
print(z)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [69]:
x=np.empty((2,3,3))
print(x)

[[[4.45057637e-308 9.34604358e-307 9.34605037e-307]
  [1.11260483e-306 1.78019354e-306 4.45066125e-308]
  [9.34605037e-307 1.60220393e-306 1.24611674e-306]]

 [[4.45057637e-308 9.34597567e-307 2.22523004e-306]
  [2.13620264e-306 4.45063578e-308 1.37961302e-306]
  [8.45596650e-307 5.73116149e-322 2.56765117e-312]]]


To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [77]:
ar= np.arange(0,51,5)
print(ar)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [78]:
arr=np.arange(0,3,.2)
print(arr)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]


In [83]:
lin = np.linspace(2,5,9)
print(lin)

[2.    2.375 2.75  3.125 3.5   3.875 4.25  4.625 5.   ]
